#!/opt/homebrew/bin/bash
# install.sh -- install these hooks so they actually fire, and REFUSE rather
# than silently install nothing.
#
# THE TRAP THIS EXISTS TO CATCH
#
# `git config core.hooksPath` overrides the repo's own hooks directory
# entirely. If a global hooksPath is set -- and on this machine one IS, at
# ~/.config/git/hooks, carrying gitleaks secret scanning, the README generator,
# and the protected-branch guard -- then copying files into .git/hooks installs
# NOTHING. Git reports no error. Every commit passes. That is the failure mode
# this script exists to prevent.
#
# WHY THIS CHAINS INSTEAD OF REFUSING
#
# The upstream exemplar installer refuses outright when hooksPath is set and
# tells you to pick: overwrite the global hooks, or unset hooksPath for this
# repo. Both answers are wrong here, because the global hooks are not
# incidental -- gitleaks is the secret-scanning gate, and dropping it to gain
# ruff checks trades a security control for a style one.
#
# So this installs a repo-local hooksPath containing SHIMS. Each shim runs the
# global hook of the same name first (preserving gitleaks, doc generation, and
# the branch guard), then this repo's hook. Either one failing fails the commit.

set -uo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(git -C "$here" rev-parse --show-toplevel 2>/dev/null)"

if [[ -z "$repo_root" ]]; then
  printf 'install.sh: not inside a git repository.\n'
  exit 1
fi

# Where the shims live. Visible name, not .githooks -- no hidden folders for
# project content (_DOCS/STANDARDS-core.md). Generated, so it is gitignored;
# the SOURCE hooks next to this script are what is tracked.
target="$repo_root/_githooks/installed"
mkdir -p "$target"

global_hooks="$(git config --global core.hooksPath || true)"
# Expand a leading ~ -- git stores the literal string, so "~/.config/git/hooks"
# would otherwise be treated as a relative directory named "~".
[[ "$global_hooks" == "~"* ]] && global_hooks="${HOME}${global_hooks#\~}"

printf '\nInstalling audiobook-pipeline hooks\n'
if [[ -n "$global_hooks" ]]; then
  printf '  chaining to global hooks at: %s\n' "$global_hooks"
else
  printf '  no global core.hooksPath -- installing repo hooks only\n'
fi

installed=0
for hook in pre-commit commit-msg pre-push post-merge; do
  src="$here/$hook"
  [[ -f "$src" ]] || { printf '  MISSING SOURCE: %s\n' "$src"; exit 1; }

  {
    printf '#!/opt/homebrew/bin/bash\n'
    printf '# GENERATED by _githooks/install.sh -- DO NOT EDIT.\n'
    printf '# Edit _githooks/%s and re-run the installer.\n' "$hook"
    printf 'set -uo pipefail\n\n'

    # stdin matters: pre-push receives the ref list on it, and a hook that
    # consumes stdin leaves nothing for the next one. Buffer it once and feed
    # both hooks their own copy.
    printf 'stdin_buf=""\n'
    printf 'if [[ ! -t 0 ]]; then stdin_buf="$(cat)"; fi\n\n'

    if [[ -n "$global_hooks" && -x "$global_hooks/$hook" ]]; then
      printf '# Global hook first: gitleaks, doc generation, branch guard.\n'
      printf 'printf "%%s" "$stdin_buf" | %q "$@" || exit $?\n\n' \
        "$global_hooks/$hook"
    fi

    printf '# This repo'"'"'s hook.\n'
    printf 'printf "%%s" "$stdin_buf" | %q "$@"\n' "$here/$hook"
  } > "$target/$hook"

  chmod +x "$target/$hook"
  printf '  installed %s\n' "$hook"
  installed=$((installed + 1))
done

git -C "$repo_root" config core.hooksPath "$target"

printf '\n%d hooks installed; core.hooksPath -> %s\n' "$installed" "$target"
printf 'Verify they actually block -- installed is not the same as working:\n'
printf '    ./_githooks/verify.sh\n\n'
